"use client";
import Link from "next/link";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";
import { Loader2 } from "lucide-react";

export function AuthForm({ mode }: { mode: "login" | "signup" }) {
  const router = useRouter();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const isSignup = mode === "signup";
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(""); if (isSignup && password !== confirm) { setError("Passwords do not match."); return; } setLoading(true); const supabase = createClient(); const result = isSignup ? await supabase.auth.signUp({ email, password }) : await supabase.auth.signInWithPassword({ email, password }); if (result.error) setError(result.error.message); else if (isSignup) setError("Check your email to confirm your account."); else router.push("/dashboard"); setLoading(false); }
  async function google() { setLoading(true); const { error } = await createClient().auth.signInWithOAuth({ provider: "google", options: { redirectTo: `${window.location.origin}/auth/callback` } }); if (error) { setError(error.message); setLoading(false); } }
  return <div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 shadow-xl shadow-slate-200/60"><div className="mb-8 text-center"><Link href="/" className="text-2xl font-bold tracking-tight text-slate-950">Blogify <span className="text-violet-600">AI</span></Link><h1 className="mt-8 text-2xl font-semibold text-slate-950">{isSignup ? "Create your account" : "Welcome back"}</h1><p className="mt-2 text-sm text-slate-500">{isSignup ? "Start turning ideas into publish-ready blogs." : "Sign in to continue writing."}</p></div><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium text-slate-700">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-violet-500 focus:ring-4 focus:ring-violet-100" /></label><label className="block text-sm font-medium text-slate-700">Password<input required minLength={6} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-violet-500 focus:ring-4 focus:ring-violet-100" /></label>{isSignup && <label className="block text-sm font-medium text-slate-700">Confirm password<input required type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-violet-500 focus:ring-4 focus:ring-violet-100" /></label>}{error && <p className="rounded-lg bg-violet-50 px-3 py-2 text-sm text-violet-800">{error}</p>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-3 font-semibold text-white transition hover:bg-violet-700 disabled:opacity-60">{loading && <Loader2 className="h-4 w-4 animate-spin" />}{isSignup ? "Sign Up" : "Log In"}</button></form><div className="my-6 flex items-center gap-3 text-xs text-slate-400"><span className="h-px flex-1 bg-slate-200" />OR<span className="h-px flex-1 bg-slate-200" /></div><button onClick={google} disabled={loading} className="w-full rounded-xl border border-slate-200 px-4 py-3 font-semibold text-slate-700 transition hover:bg-slate-50">Sign in with Google</button><p className="mt-6 text-center text-sm text-slate-500">{isSignup ? "Already have an account?" : "New to Blogify AI?"} <Link href={isSignup ? "/login" : "/signup"} className="font-semibold text-violet-600 hover:text-violet-700">{isSignup ? "Log in" : "Sign up"}</Link></p></div>;
}
