from operator import add
from typing import Annotated, Optional, TypedDict

from pydantic import BaseModel, Field


class Task(BaseModel):
    """A single section-writing task for a worker node"""

    section_title: str = Field(description="title/heading for this sections")
    order: int = Field(description="What shoudl be the order of this section in final post i-e 1,2,3 etc")
    description: str = Field(description="Detailed Instructions on what to cover in this section")
    word_count: Optional[int] = Field(description="Total/estimated words for this section should be around 250 to 400")
    keywords: Optional[list] = Field(default=None, description="Key terms or concepts that should be covered in this section")
    relevant_facts: Optional[str] = Field(default=None, description="Facts from research that are relevant to this section")


class Plan(BaseModel):
    """Complete Blog plan generated by orchestrator"""

    title: str = Field(description="Overall blog post title")
    intro_summary: str = Field(description="One-Line summary for the blog's angle/thesis , for context")
    tasks: list[Task] = Field(description="List of task written in this sections", min_length=1, max_length=8)


class RouterDecision(BaseModel):
    """Decision about whether external research is needed before planning the blog"""

    needs_search: bool = Field(description="Whether web search is needed for the topic")
    search_queries: list[str] = Field(default_factory=list, min_length=0, max_length=4, description="2-4 focused search queries if search is needed")
    reason: str = Field(description="Brief reason for the routing decision")


class EvidenceItem(BaseModel):
    """One search result or source snippet used as evidence"""

    title: str = Field(description="Title of the source or search result")
    url: str = Field(description="URL of the source")
    content: str = Field(description="Relevant snippet or content from the source")


class EvidencePack(BaseModel):
    """Evidence gathered for a single search query"""

    query: str = Field(description="Search query used to collect the evidence")
    results: list[EvidenceItem] = Field(default_factory=list, description="Evidence items returned for this query")


class BlogState(TypedDict, total=False):
    topic: str
    router_decision: RouterDecision
    evidence_packs: list[EvidencePack]
    evidence_summary: str
    plan: Plan
    completed_sections: Annotated[list[str], add]
    final_response: str
    final_blog: str


class WorkerState(TypedDict):
    task: Task
    completed_sections: Annotated[list[str], add]
